export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE_DETAIL = "FETCH_MOVIE_DETAIL";
export const UPDATE_SEARCH_VALUE = "UPDATE_SEARCH_VALUE";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const FETCH_TOTAL_RESULTS = "FETCH_TOTAL_RESULTS";
